version: "3.7"
services:
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: gorod
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  mysql_client:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

volumes:
  mysql_db_data_container:
